/*
INSERT INTO beer(name,abv) VALUES ('Bartek IPA',6.16);
INSERT INTO beer(name,abv) VALUES ('Mateusz APA',3.16);
INSERT INTO beer(name,abv) VALUES ('Kacper Pils',1.16);
*/
/*
INSERT INTO user(login,password,name,lastname,mail) VALUES ('test','test','bartek','gawron','cos@cos.pl');
INSERT INTO user(login,password,name,lastname,mail) VALUES ('Bartek1','test','bartek','gawron','cos@cos.pl');
INSERT INTO user(login,password,name,lastname,mail) VALUES ('Bartek2','test','bartek','gawron','cos@cos.pl');
*/
DROP TABLE IF EXISTS BEERS CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE BEERS(
  BEER_ID BIGINT NOT NULL,
  NAME VARCHAR (255),
  ABV VARCHAR (255),
  RATINGS REAL
);

CREATE TABLE USERS(
  USER_ID BIGINT NOT NULL,
  LOGIN VARCHAR (255) NOT NULL,
  PASSWORD VARCHAR (255) NOT NULL,
  NAME VARCHAR (255),
  LAST_NAME VARCHAR (255),
  REGISTRATION_NUMBER VARCHAR (255),
  MAIL VARCHAR (255) NOT NULL
);

ALTER TABLE BEERS
  ADD CONSTRAINT PK_BEERS
PRIMARY KEY (BEER_ID);

ALTER TABLE USERS
  ADD CONSTRAINT PK_USERS
PRIMARY KEY (USER_ID);


INSERT INTO BEERS(BEER_ID,NAME,ABV,RATINGS) VALUES (0,'Bartek IPA','6.16',312);
INSERT INTO BEERS(BEER_ID,NAME,ABV,RATINGS) VALUES (1,'Mateusz APA','3.16',50);
INSERT INTO BEERS(BEER_ID,NAME,ABV,RATINGS) VALUES (2,'Kacper Pils','1.16',23);

INSERT INTO USERS(USER_ID, LOGIN, PASSWORD, NAME, LAST_NAME, REGISTRATION_NUMBER, MAIL) VALUES (1,'Bartek12','123','Bartosz','Gawron','1','cos@cos.pl');
INSERT INTO USERS(USER_ID, LOGIN, PASSWORD, NAME, LAST_NAME, REGISTRATION_NUMBER, MAIL) VALUES (2,'Mati12','123','Mateusz','Gawron','2','cos@cos.pl');

/*CREATE SEQUENCE DEFAULTDBSEQ START 1;*/
/*CREATE OR REPLACE VIEW USER AS SELECT * FROM USERS;*/

COMMIT;